services:
  app:
    build: .
    container_name: football_app
    volumes:
      - .:/app
      - ./requirements.txt:/app/requirements.txt

    env_file:
      - path: .env
        required: True
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

    command: tail -f /dev/null  # Keeps the container alive

  db:
    image: postgres:16
    container_name: football_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: football
    ports:
      - "5432:5432"
    volumes:
      - football_db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: football_redis
    ports:
      - "6379:6379"
    volumes:
      - football_redis_data:/data

volumes:
  py_files:
  football_db_data:
  football_redis_data:
  
